# Generated by Django 3.0.2 on 2020-01-28 15:37

from django.db import migrations
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200128_1529'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', login.models.TreeManeger()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
