# Generated by Django 3.0.2 on 2020-01-24 11:50

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashBourdBd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True, auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('priority',
                 models.IntegerField(blank=True, choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1,
                                     null=True)),
                ('types',
                 models.IntegerField(blank=True, choices=[(1, 'Бугалтерия'), (2, 'It отделл')], default=1, null=True)),
                ('status',
                 models.IntegerField(choices=[(1, 'Открыта'), (2, 'В работе'), (3, 'Ждет контроля'), (4, 'Закрыта')],
                                     default=1)),
                ('File', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
            managers=[
                ('objects_test', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ticketChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
