# Generated by Django 3.0.2 on 2020-01-28 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('label_ListPage', '0003_auto_20200125_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricaldashBourdBd',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data', models.DateField(auto_created=True, blank=True, db_index=True, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Низкий'), (2, 'Нормальный'), (3, 'Срочный')], default=1, null=True)),
                ('types', models.IntegerField(blank=True, choices=[(1, 'Бугалтерия'), (2, 'It отделл')], default=1, null=True)),
                ('status', models.IntegerField(choices=[(1, 'В обработке'), (2, 'Отправленно на доработку'), (3, 'В работе'), (4, 'Выполнена'), (5, 'Закрыта')], default=1)),
                ('File', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autors', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager_a', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dash bourd bd',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
