# Generated by Django 3.0.2 on 2020-01-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_ListPage', '0004_historicaldashbourdbd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashbourdbd',
            name='types',
        ),
        migrations.RemoveField(
            model_name='historicaldashbourdbd',
            name='types',
        ),
    ]
