# Generated by Django 3.0.2 on 2020-01-28 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('label_ListPage', '0006_auto_20200128_1531'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dashbourdbd',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='types',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='types',
            name='meneger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='menegerTypes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
