# Generated by Django 3.0.2 on 2020-01-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label_ListPage', '0008_auto_20200128_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchat',
            name='post',
            field=models.ForeignKey(db_column='pk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='label_ListPage.dashBourdBd'),
        ),
    ]
